package com.localfood.foodapp

import android.Manifest
import android.annotation.SuppressLint
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.webkit.CookieManager
import android.webkit.JavascriptInterface
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.ComponentActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat

class MainActivity : ComponentActivity() {
    companion object {
        // Replace this with your live Render URL before building the app.
        const val SITE_URL = "https://YOUR-RENDER-SERVICE.onrender.com/"
        const val CHANNEL_ID = "food_order_updates"
        var activeActivity: MainActivity? = null
    }

    private lateinit var webView: WebView
    private val siteHost: String by lazy { Uri.parse(SITE_URL).host ?: "" }

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        activeActivity = this
        createNotificationChannel()
        askNotificationPermission()

        webView = WebView(this)
        setContentView(webView)
        CookieManager.getInstance().setAcceptCookie(true)
        CookieManager.getInstance().setAcceptThirdPartyCookies(webView, true)
        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true
        webView.settings.loadsImagesAutomatically = true
        webView.settings.javaScriptCanOpenWindowsAutomatically = true
        webView.settings.setSupportMultipleWindows(false)
        webView.webChromeClient = WebChromeClient()
        webView.addJavascriptInterface(NativeBridge(), "FoodNative")
        webView.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
                val uri = request.url
                if (uri.scheme == "http" || uri.scheme == "https") {
                    if (uri.host == siteHost) {
                        if (isAdminPath(uri.path.orEmpty())) {
                            view.loadUrl(SITE_URL)
                            return true
                        }
                        return false
                    }
                    // Keep Google sign-in and payment provider pages in the WebView so
                    // the existing site flow can attempt to complete. Some identity providers
                    // may restrict embedded WebViews; see README for this limitation.
                    return false
                }
                return true
            }

            override fun onPageFinished(view: WebView, url: String) {
                super.onPageFinished(view, url)
                if (!url.startsWith(SITE_URL.substringBeforeLast("/") + "/")) return
                if (isAdminPath(Uri.parse(url).path.orEmpty())) {
                    view.loadUrl(SITE_URL)
                    return
                }
                startOrderStatusPolling()
            }
        }
        webView.loadUrl(SITE_URL)
    }

    private fun isAdminPath(path: String): Boolean =
        path == "/admin" || path.startsWith("/admin/") || path.startsWith("/api/admin")

    private fun startOrderStatusPolling() {
        // Local notifications are generated by Android itself. The app checks the
        // authenticated website session every 20 seconds while the WebView is active.
        val script = """
            (function() {
              if (window.__foodPollTimer) clearInterval(window.__foodPollTimer);
              async function checkFoodOrderStatuses() {
                try {
                  const response = await fetch('/api/mobile/orders/statuses', {
                    method: 'GET', credentials: 'same-origin', cache: 'no-store'
                  });
                  if (!response.ok) return;
                  const data = await response.json();
                  if (!data.success || !Array.isArray(data.orders)) return;
                  const key = 'food_order_statuses_v1';
                  const previous = JSON.parse(localStorage.getItem(key) || '{}');
                  const firstCheck = !localStorage.getItem(key);
                  for (const order of data.orders) {
                    const id = String(order.id);
                    const oldStatus = previous[id];
                    if (!firstCheck && oldStatus && oldStatus !== 'delivered' && order.status === 'delivered') {
                      FoodNative.showOrderNotification(
                        'Your food is ready!',
                        'Order #' + id + ' has been marked completed.',
                        id
                      );
                    }
                    previous[id] = order.status;
                  }
                  localStorage.setItem(key, JSON.stringify(previous));
                } catch (e) { /* Retry on the next polling cycle. */ }
              }
              checkFoodOrderStatuses();
              window.__foodPollTimer = setInterval(checkFoodOrderStatuses, 20000);
            })();
        """.trimIndent()
        webView.evaluateJavascript(script, null)
    }

    inner class NativeBridge {
        @JavascriptInterface fun appVersion(): String = "1.1.0"

        @JavascriptInterface
        fun showOrderNotification(title: String, body: String, orderId: String) {
            runOnUiThread {
                if (Build.VERSION.SDK_INT >= 33 && ContextCompat.checkSelfPermission(
                        this@MainActivity, Manifest.permission.POST_NOTIFICATIONS
                    ) != PackageManager.PERMISSION_GRANTED) return@runOnUiThread
                val launchIntent = Intent(this@MainActivity, MainActivity::class.java)
                val pendingIntent = PendingIntent.getActivity(
                    this@MainActivity, orderId.hashCode(), launchIntent,
                    PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
                )
                val notification = androidx.core.app.NotificationCompat.Builder(this@MainActivity, CHANNEL_ID)
                    .setSmallIcon(android.R.drawable.ic_dialog_info)
                    .setContentTitle(title)
                    .setContentText(body)
                    .setStyle(androidx.core.app.NotificationCompat.BigTextStyle().bigText(body))
                    .setContentIntent(pendingIntent)
                    .setAutoCancel(true)
                    .setPriority(androidx.core.app.NotificationCompat.PRIORITY_HIGH)
                    .build()
                getSystemService(NotificationManager::class.java).notify(orderId.hashCode(), notification)
            }
        }
    }

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(CHANNEL_ID, "Order updates", NotificationManager.IMPORTANCE_HIGH)
            channel.description = "Notifications when your food order is completed"
            getSystemService(NotificationManager::class.java).createNotificationChannel(channel)
        }
    }

    private fun askNotificationPermission() {
        if (Build.VERSION.SDK_INT >= 33 && ContextCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 900)
        }
    }

    override fun onBackPressed() {
        if (::webView.isInitialized && webView.canGoBack()) {
            val previous = webView.copyBackForwardList().getItemAtIndex(webView.copyBackForwardList().currentIndex - 1)
            if (previous != null && isAdminPath(Uri.parse(previous.url).path.orEmpty())) {
                webView.loadUrl(SITE_URL)
            } else webView.goBack()
        } else super.onBackPressed()
    }

    override fun onDestroy() {
        if (activeActivity === this) activeActivity = null
        super.onDestroy()
    }
}
